[project]
name = "canvas-copilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Cikal Merdeka", email = "mcikalmerdeka@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "openai>=3.13.0",
    "python-dotenv>=1.2.3",
    "streamlit>=1.63.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
